<?php

namespace AppBundle\Repository;

/**
 * StudentsInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudentsInfoRepository extends \Doctrine\ORM\EntityRepository
{
}
